# Copyright (c) 2023 Copyright (c) 2021-2022 Robert Bosch Manufacturing Solutions GmbH
# Copyright (c) 2023 Contributors to the Eclipse Foundation

# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.

# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# SPDX-License-Identifier: Apache-2.0
name: Veracode Scan

on:
  schedule:
    - cron: 0 2 * * 0
  workflow_dispatch:

jobs:
  veracode-scan-registry:
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: release
      - name: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build with maven
        run: |
          mvn clean package -DskipTests
          export REGISTRY_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "REGISTRY_VERSION=$REGISTRY_VERSION" >> $GITHUB_ENV
      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "Digital Twin Registry"
          createprofile: false
          filepath: "backend/target/digital-twin-registry-backend-${{ env.REGISTRY_VERSION }}.jar"
          vid: '${{ secrets.VERACODE_API_ID || secrets.ORG_VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY || secrets.ORG_VERACODE_API_KEY }}'